### ISSUE TITLE
as I keep a user session

### ISSUE THREAD

**Issue by newmesiss** [jay3dec/AngularJS_Firebase_Part6#1]
CommonProp service the user loses every time the Welcome view is refreshed, how can I avoid losing and maintaining session?

``` javascript
.service('CommonProp', function() {
    var user = '';

    return {
        getUser: function() {
            return user;
        },
        setUser: function(value) {
            user = value;
        }
    };
});
```

**Comment by jay3dec** [comment]
Yes, this is an issue and I'll address it in the coming series part using [ngCookie](https://docs.angularjs.org/api/ngCookies)
